include ../../mk/flags.mk
include ../../mk/build.mk

all:
	cd term && make all
	cd init && make all
	cd test && make all
	cd ls && make all

clean:
	cd term && make clean
	cd init && make clean
	cd test && make clean
	cd ls && make clean

