name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: nasm
      run: sudo apt install nasm
    
    - name: build
      run: make

  build-osx:
    runs-on: macos-11.0
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: brew install make

    - name: gcc
      run: brew install gcc-10

    - name: nasm
      run: brew install nasm
    
    - name: build
      run: make