name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: binutils
      run: brew install i686-elf-binutils

    - name: nasm
      run: brew install nasm

    - name: llvm
      run: brew install llvm
      
    - name: build
      run: make
