name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check markdown links
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          config-file: '.github/workflows/.mlc_config.json'
        continue-on-error: false

  build-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: install-prereqs
        run: sudo apt install -y wget make nasm patch clang-format build-essential binutils gcc-10 git iwyu curl mtools dosfstools

      - name: lint
        run: cd src;make lint

#      - name: header-check
#        run: cd src;make header-check

      - name: build
        run: cd src;make

  build-osx:
    runs-on: macos-10.15
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: install-prereqs
        run: brew install make x86_64-elf-gcc nasm clang-format wget git iwyu curl mtools dosfstools
        
      - name: lint
        run: cd src;make lint

 #     - name: header-check
 #       run: cd src;make header-check

      - name: build
        run: cd src;make
